export * from "./dashboard/dashboard";
export * from "./students/students";
export * from "./login/LoginType";
export * from "./login/LoginAdmin";
export * from "./login/LoginTeacher";
export * from "./events/events";
export * from "./landingPage/landing";
export * from "./timetable/table";
export * from "./GestaoDocente/docents";
